name: "Podcast Generator"
author: "Akhil Kadangode"
description: "Generate podcast episodes from YAML file"
runs:
  using: "docker"
  main: "Dockerfile"
branding:
  color: "blue"
  icon: "mic"
inputs:
  email:
    description: "Committer's email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "Committer's name"
    required: true
    default: ${{ github.actor }}